language: python
script:
  - python manage.py test
notifications:
    email:
        recipients:
           - sqrtlabs@hotmail.com
           - saadi4567@gmail.com
        on_success: always
        on_failure: always
