version: '3.7'

services: 
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000 
        # command: gunicorn bookstore_project.wsgi -b 0.0.0.0:8000
        # command: python /code/manage.py rqworker
        volumes: 
            - .:/code
        ports: 
            - 8000:8000
        depends_on: 
            - db
    db:
        image: postgres:12
        volumes: 
            - postgres_data:/var/lib/postgresql/data/


    redis:
        image: redis:alpine



volumes: 
    postgres_data:
